// batalha-dos-frameworks/front-vue/src/views/home/Home.vue
<template>
  <div>
    <h1>{{msg}}</h1>
    <h2>{{legenda}}</h2>

    <input type="text" v-bind:value="legenda" />
    <!-- OU -->
    <!-- <input type="text" :value="legenda" /> -->

    <button @click="resetLegenda">Reset Legenda</button>
  </div>
</template>

<script>
export default {
  props: ["msg"],
  data: () => ({ legenda: "Estou no Vue" }),
  methods: {
    resetLegenda() {
      console.log("Evento de click no Vue");
    }
  }
};
</script>

<style>
</style>

// batalha-dos-frameworks/front-react/src/views/home/Home.jsx
import React from "react";

import "./Home.css";

const Home = (props) => {
  let legenda = "Estou no React";

  function resetLegenda() {
    console.log("Evento de click no React!");
  }

  return (
    <div className="home">
      <h1>{props.msg}</h1>
      <h2>{legenda}</h2>

      <input type="text" value={legenda} readOnly />

      <button onClick={resetLegenda}>Reset Legenda</button>
    </div>
  );
};

export default Home;
