// batalha-dos-frameworks/front-angular/src/app/views/home/home.component.ts
import { Component, OnInit, Input } from "@angular/core";

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.css"],
})
export class HomeComponent implements OnInit {
  @Input() msg: string;
  legenda: string = "Estou no Angular";

  constructor() {}

  ngOnInit(): void {}

  // Função do componente
  resetLegenda(): void {
    console.log("Evento de click no angular!");
  }
}

<h1>{{ msg }}</h1>
<h2>{{ legenda }}</h2>

<!-- []: bind de valor -->
<input type="text" [value]="legenda" />

<!-- (): bind de função -->
<button (click)="resetLegenda()">Reset Legenda</button>

// batalha-dos-frameworks/front-react/src/views/home/Home.jsx
import React from "react";

import "./Home.css";

const Home = (props) => {
  let legenda = "Estou no React";

  function resetLegenda() {
    console.log("Evento de click no React!");
  }

  return (
    <div className="home">
      <h1>{props.msg}</h1>
      <h2>{legenda}</h2>

      <input type="text" value={legenda} readOnly />

      <button onClick={resetLegenda}>Reset Legenda</button>
    </div>
  );
};

export default Home;
